### ISSUE TITLE
No handler matched request to /openidprocess

### ISSUE THREAD

**Issue by strk** [trac-hacks/authopenid-plugin#31]
I get a 'No handler matched request to /openidprocess' error on returning from the authenticating peer.
Using trac-authopenid 0.4.1-2 (Debian 8 package) with Trac 1.0.1.

Ideas ?

**Comment by rjollos** [comment]
Have you confirmed that the plugin is loading? You might want to [check the logs](https://trac.edgewall.org/wiki/TracTroubleshooting#ChecktheLogs).

**Comment by rjollos** [comment]
Feel free to reopen if you still need assistance. Generally [InstallationIssues](https://trac.edgewall.org/wiki/InstallationIssue) should be asked on the [MailingList](http://trac.edgewall.org/wiki/MailingList).
