### ISSUE TITLE
Plugin upgrade to last version

### ISSUE THREAD

**Issue by txomon** [trac-hacks/authopenid-plugin#5]
Hi,

I am interested in using your plugin, but asking in #trac (irc.freenode.net), they told me that thought actually might work, it wont in next versions.

Here I paste a transcript of the irc explanation the gave me:

> <hasienda> txomon: I've just taken a look at its source.
> <hasienda> txomon: Sees quite elaborated, so give it a try.
> <hasienda> txomon: It should work with Trac 0.12 .. 1.0,
> <hasienda> txomon: but is not ready for upcoming 1.1.x/1.2 that is meant to finally drop old db API
> <hasienda> txomon: but a lot of Trac plugins currently share this state, the Trac 1.0 db API is not widely adopted yet.
> <hasienda> txomon: what could become more of a problem is the version-free db schema of AuthOpenidPlugin
> <hasienda> txomon: If you care, please urge the author/maintainers to move to a versioned schema (with 'authopenid_version' stored in Trac db table 'sysem')
> <hasienda> txomon: the issue is with https://github.com/dairiki/authopenid-plugin/blob/master/authopenid/authopenid.py#L241 ff
> <hasienda> txomon: this check for table existence has been discussed quite a lot lately. It must be avoided, because it breaks the whole upgrade check procedure in recent Trac versions,
> <hasienda> txomon: and will probably even prevent Trac core itself from upgrading its db
> <txomon> ok
> <hasienda> txomon: But this is all known, and a fix could be implemented similar to what has been discussed in http://trac-hacks.org/ticket/9521

Hope this helps you identify the issue (I am not familiarized with the API yet),

Cheers,

Javier Domingo

**Comment by rjollos** [comment]
See #32.
